apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:  
    app: notification-service
spec:
  selector:
    app: notification-service
  # type: NodePort
  type: LoadBalancer
  ports:
  - port: 9999
    targetPort: 9999
    protocol: TCP
    # nodePort: 30289
